src/Entity/Inscription.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InscriptionRepository")
 */
class Inscription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateInscr;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPassage;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="inscriptions")
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Trajet", inversedBy="inscriptions")
     */
    private $trajet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateInscr(): ?\DateTimeInterface
    {
        return $this->dateInscr;
    }

    public function setDateInscr(\DateTimeInterface $dateInscr): self
    {
        $this->dateInscr = $dateInscr;

        return $this;
    }

    public function getNbPassage(): ?int
    {
        return $this->nbPassage;
    }

    public function setNbPassage(int $nbPassage): self
    {
        $this->nbPassage = $nbPassage;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getTrajet(): ?Trajet
    {
        return $this->trajet;
    }

    public function setTrajet(?Trajet $trajet): self
    {
        $this->trajet = $trajet;

        return $this;
    }
}

src/Entity/Trajet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrajetRepository")
 */
class Trajet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villeDep;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villeDest;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDep;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombrePlacesMax;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="trajets")
     */
    private $conducteur_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="trajet")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Inscription", mappedBy="trajet")
     */
    private $inscriptions;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->inscriptions = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVilleDep(): ?string
    {
        return $this->villeDep;
    }

    public function setVilleDep(string $villeDep): self
    {
        $this->villeDep = $villeDep;

        return $this;
    }

    public function getVilleDest(): ?string
    {
        return $this->villeDest;
    }

    public function setVilleDest(string $villeDest): self
    {
        $this->villeDest = $villeDest;

        return $this;
    }

    public function getDateDep(): ?\DateTimeInterface
    {
        return $this->dateDep;
    }

    public function setDateDep(\DateTimeInterface $dateDep): self
    {
        $this->dateDep = $dateDep;

        return $this;
    }

    public function getNombrePlacesMax(): ?int
    {
        return $this->nombrePlacesMax;
    }

    public function setNombrePlacesMax(int $nombrePlacesMax): self
    {
        $this->nombrePlacesMax = $nombrePlacesMax;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(?int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getConducteurId(): ?Utilisateur
    {
        return $this->conducteur_id;
    }

    public function setConducteurId(?Utilisateur $conducteur_id): self
    {
        $this->conducteur_id = $conducteur_id;

        return $this;
    }

    //Retourne le nombre de places restantes pour le trajet
    public function calculerNbPlacesRestantes():int
    {
        $nb = 0;
        foreach( $this->getInscriptions() as $inscr )
        {
            $nb = $nb + $inscr->getNbPassage();
        }
        return $this->getNombrePlacesMax() - $nb;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setTrajet($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getTrajet() === $this) {
                $commentaire->setTrajet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setTrajet($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->contains($inscription)) {
            $this->inscriptions->removeElement($inscription);
            // set the owning side to null (unless already changed)
            if ($inscription->getTrajet() === $this) {
                $inscription->setTrajet(null);
            }
        }

        return $this;
    }
}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use App\Entity\Trajet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class InscriptionType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('NbPassage',IntegerType::class,['constraints'=>[new NotBlank(),]])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Entity\Trajet;
use App\Entity\Utilisateur;
use App\Form\InscriptionType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class InscriptionController extends AbstractController
{

    /**
     * @Route("/{_locale}/inscription/index", name="inscription")
     */
    public function index()
    {
        return $this->render('inscription/index.html.twig', [
            'controller_name' => 'InscriptionController',
        ]);
    }

    /**
     * Lister tous les inscriptions.
     * @Route("/{_locale}/inscription", name="inscription.list")
     * @return Response
     */
    public function list() : Response
    {
    $inscriptions = $this->getDoctrine()->getRepository(Inscription::class)->findAll();
    return $this->render('inscription/list.html.twig', [
    'inscriptions' => $inscriptions,
    ]);
    }

    /**
     * Créer un nouveau inscription.
     * @Route("/{_locale}/nouveau-inscription/{idtrajet}", name="inscription.create")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param Trajet $idtrajet
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $em, Trajet $idtrajet) : Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (($idtrajet->calculerNbPlacesRestantes() - $inscription->getNbPassage()) >= 0 )
            {
                $date = new \DateTime("+0 days");
                $inscription->setDateInscr($date);

                $utilisateur= new Utilisateur();
                $utilisateur = $this->getUser();
                $inscription->setUtilisateur($utilisateur);

                $inscription->setTrajet($idtrajet);

                $em->persist($inscription);
                $em->flush();
            }
            
            return $this->redirectToRoute("trajet.show",['id'=>$idtrajet->getId()]);
        }
        return $this->render('inscription/create.html.twig', [
        'form' => $form->createView(),'trajet' =>$idtrajet,
        ]);
    }

    /** 
    * @Route("/{_locale}/inscription/{id}/show", name="inscription.show")
    * @param Inscription $inscription
    * @return Response
    */
    public function show(inscription $inscription) : Response
    {
        return $this->render('inscription/show.html.twig', [
            'inscription' => $inscription,
            ]);
    }

    /**
    * Éditer un inscription.
    * @Route("/{_locale}/inscription/{id}/edit", name="inscription.edit")
    * @param Request $request
    * @param EntityManagerInterface $em
    * @return RedirectResponse|Response
    */
    public function edit(Request $request, inscription $inscription, EntityManagerInterface $em) : Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);
        
        $utilisateur= new Utilisateur();
        $utilisateur = $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            if (
                ($inscription->getTrajet()->calculerNbPlacesRestantes() - $inscription->getNbPassage() >= 0)
                &&
                ($inscription->getUtilisateur()->getId() === $utilisateur->getId())
               )
            {
                $em->flush();
            }
            return $this->redirectToRoute("trajet.show",['id'=>$inscription->getTrajet()->getId()]);
        }
        return $this->render('inscription/create.html.twig', [
        'form' => $form->createView(),'trajet' =>$inscription->getTrajet(),
        ]);
    }

    /**
    * Supprimer un inscription.
    * @Route("/{_locale}/inscription/{id}/delete", name="inscription.delete")
    * @param Request $request
    * @param Inscription $inscription
    * @param EntityManagerInterface $em
    * @return Response
    */
    public function delete(Request $request, Inscription $inscription, EntityManagerInterface $em) : Response
    {
        $form = $this->createFormBuilder()
        ->setAction($this->generateUrl('inscription.delete', ['id' => $inscription->getId()]))
        ->getForm();
        $form->handleRequest($request);
        
        $utilisateur= new Utilisateur();
        $utilisateur = $this->getUser();

        if ( ! $form->isSubmitted() || ! $form->isValid()) {
            return $this->render('inscription/delete.html.twig', [
            'inscription' => $inscription,
            'form' => $form->createView(),
            ]);
        }
        
        $em = $this->getDoctrine()->getManager();
        if ( $inscription->getUtilisateur()->getId() === $utilisateur->getId() || in_array('ROLE_ADMIN',$utilisateur->getRoles()) )
        {
            $em->remove($inscription);
            $em->flush();
        }
        return $this->redirectToRoute("trajet.show",['id'=>$inscription->getTrajet()->getId()]);
    }
}

templates/inscription/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{{ 'creation-modification-reservation'|trans }}</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">{{ 'enregistrer'|trans }}</button>
            </div>
        </div>
        {{ form_end(form) }}
{% endblock %}

templates/inscription/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="alert alert-danger">
        <strong>{{ 'avertissement'|trans }}</strong> {{ 'msg-suppr-inscription'|trans }}
        <ul>
            <li><strong>{{ 'username'|trans }}: </strong> {{ inscription.utilisateur.username }}</li>
            <li><strong>{{ 'date'|trans }}: </strong>{{ inscription.dateInscr|date('d/m/Y') }}</li>
            <li><strong>{{ 'nombre-passagers'|trans }}: </strong>{{ inscription.nbPassage }}</li>

        </ul>
    </div>
    {{ form_start(form, {'attr': {'class': 'navbar-form navbar-left'}}) }}
    {{ form_widget(form) }}
    
        <a href="/{{app.request.locale }}/trajet/{{inscription.trajet.id}}/show"  role="button">
        <button type="submit" class="btn btn-success">{{ 'cancel'|trans }}</button></a>

        <button type="submit" class="btn btn-danger" onclick="return confirm('{{ "confirm"|trans }}')">
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            {{ 'suppr'|trans }}
    </button>
    {{ form_end(form) }}
{% endblock %}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello InscriptionController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/wampserver/www/projetWeb/Covoit/src/Controller/InscriptionController.php'|file_link(0) }}">src/Controller/InscriptionController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/wampserver/www/projetWeb/Covoit/templates/inscription/index.html.twig'|file_link(0) }}">templates/inscription/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/inscription/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="table text-center">
        <tr>
            <th class="active text-center">{{ 'date'|trans }}</th>
            <th class="active text-center">{{ 'depart'|trans }}</th>
            <th class="active text-center">{{ 'arrivee'|trans }}</th>
            <th class="active text-center">{{ 'pl-rest'|trans }}</th>
            <th class="active text-center">{{ 'status2'|trans }}</th>
            <th class="active text-center">{{ 'conducteur'|trans }}</th>
            <th class="active text-center">{{ 'action'|trans }}</th>

        </tr>

        {% for inscription in inscriptions %}
            <tr>
                <td>{{ inscription.trajet.dateDep|date("d/m/Y") }}</td>
                <td>{{ inscription.trajet.villeDep }}</td>
                <td>{{ inscription.trajet.villeDest }}</td>
                <td>{{ inscription.trajet.calculerNbPlacesRestantes }}</td>
                {% if inscription.trajet.statut == 1 %}
                    <td>{{ 'dispo'|trans }}</td>
                {% elseif inscription.trajet.statut == 2 %}
                    <td>{{ 'pas-dispo'|trans }}</td>
                {% endif %}
                <td>{{ inscription.trajet.conducteurId.username }}</td>

                {% if (not app.user) %}
                    <td><a href={{ path("trajet.show",
                            {id : inscription.trajet.id,_locale:app.request.locale} ) }} class="btn btn-info">{{ 'show'|trans }}</a></td>
                {% else %}
                    {% if (app.user.username == inscription.utilisateur.username) %}
                    <td><a href={{ path("inscription.edit",
                            {id : inscription.id,_locale:app.request.locale} )}} class="btn btn-primary">{{ 'edit'|trans }}</a>
                        <a href={{ path("inscription.delete",
                            {id : inscription.id,_locale:app.request.locale} ) }} class="btn btn-danger">{{ 'suppr'|trans }}</a>
                        <a href={{ path("trajet.show",
                            {id : inscription.trajet.id,_locale:app.request.locale} ) }} class="btn btn-info">{{ 'show'|trans }}</a></td>
                    {% elseif is_granted('ROLE_ADMIN') %}
                        <td><a href={{ path("inscription.delete",
                                {id : inscription.id,_locale:app.request.locale} ) }} class="btn btn-danger">{{ 'suppr'|trans }}</a>
                            <a href={{ path("trajet.show",
                                {id : inscription.trajet.id,_locale:app.request.locale} ) }} class="btn btn-info">{{ 'show'|trans }}</a></td>
                    {% else %}
                        <td><a href={{ path("trajet.show",
                                {id : inscription.trajet.id,_locale:app.request.locale} ) }} class="btn btn-info">{{ 'show'|trans }}</a></td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}